name: Build and Deploy~
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0
          cache: true
      - run: dotnet restore --locked-mode 
      - run: dotnet publish *.csproj -c Release -o release --nologo
      - uses: JamesIves/github-pages-deploy-action@4.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot